#!/usr/bin/env bash
set -euo pipefail

SELF=$(readlink -f -- "$0")
SCRIPT_DIR=$(cd -- "$(dirname -- "$SELF")" && pwd)

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    caller=${USER:-$(id -un)}
    exec sudo env ARCHANGEL_CALLER="$caller" bash "$SELF" "$@"
fi

say() {
    printf '%s\n' "$*"
}

die() {
    printf 'install.sh: %s\n' "$*" >&2
    exit 1
}

ask() {
    local prompt=$1 default=$2 value
    read -r -p "$prompt [$default]: " value </dev/tty
    printf '%s' "${value:-$default}"
}

yes_no() {
    local prompt=$1 default=${2:-Y} answer suffix
    if [[ "$default" == "Y" ]]; then suffix='Y/n'; else suffix='y/N'; fi
    read -r -p "$prompt [$suffix]: " answer </dev/tty
    answer=${answer:-$default}
    [[ "$answer" =~ ^[Yy]$ ]]
}

valid_username() {
    [[ "$1" =~ ^[a-z_][a-z0-9_-]*[$]?$ ]]
}

install_acl_package() {
    if command -v setfacl >/dev/null 2>&1; then
        return
    fi

    say "The POSIX ACL tools are required but setfacl was not found."
    yes_no "Install the ACL package now?" Y || die "ACL tools are required"

    if command -v pacman >/dev/null 2>&1; then
        pacman -S --needed acl
    elif command -v apt-get >/dev/null 2>&1; then
        apt-get install -y acl
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y acl
    elif command -v zypper >/dev/null 2>&1; then
        zypper --non-interactive install acl
    else
        die "could not identify a supported package manager; install the acl package manually and rerun"
    fi
}

say "Archangel bootstrap"
say "This prepares a separate Linux account and installs the local access-management tools."
say

caller=${ARCHANGEL_CALLER:-}
if [[ -z "$caller" || "$caller" == root ]] || ! getent passwd "$caller" >/dev/null; then
    caller=$(logname 2>/dev/null || true)
fi
if [[ -z "$caller" || "$caller" == root ]] || ! getent passwd "$caller" >/dev/null; then
    caller=$(awk -F: '$3 >= 1000 && $3 < 60000 {print $1; exit}' /etc/passwd)
fi
[[ -n "$caller" ]] || die "could not determine the human/owner account"

owner_user=$(ask "Human account whose files may be shared with the agent" "$caller")
getent passwd "$owner_user" >/dev/null || die "user '$owner_user' does not exist"

agent_user=$(ask "Unix account to run the agent" "hermes")
valid_username "$agent_user" || die "'$agent_user' is not a valid simple Unix username"
[[ "$agent_user" != "$owner_user" ]] || die "agent and owner accounts must be different"

agent_comment=$(ask "Account description" "Archangel agent")

install_acl_package
command -v runuser >/dev/null 2>&1 || die "runuser is required (normally provided by util-linux)"

if getent passwd "$agent_user" >/dev/null; then
    say "User '$agent_user' already exists."
    yes_no "Use the existing account?" N || die "choose another agent username and rerun"
else
    say "Creating '$agent_user' with its own home directory..."
    useradd -m -s /bin/bash -c "$agent_comment" "$agent_user"
fi

journal_enabled=no
if getent group systemd-journal >/dev/null 2>&1; then
    if yes_no "Allow '$agent_user' to read the systemd journal for diagnostics?" Y; then
        usermod -aG systemd-journal "$agent_user"
        journal_enabled=yes
    fi
else
    say "No systemd-journal group found; skipping journal group setup."
fi

install -d -m 0755 /etc
cat > /etc/archangel.conf <<CFG
# Generated by Archangel install.sh
ARCHANGEL_AGENT_USER='$agent_user'
ARCHANGEL_OWNER_USER='$owner_user'
CFG
chmod 0644 /etc/archangel.conf

install -d -m 0750 /var/lib/archangel
touch /var/lib/archangel/grants.tsv /var/lib/archangel/traversal.tsv
chmod 0640 /var/lib/archangel/grants.tsv /var/lib/archangel/traversal.tsv

install -m 0755 "$SCRIPT_DIR/bin/archangel-access" /usr/local/bin/archangel-access
install -m 0755 "$SCRIPT_DIR/bin/archangel-diagnostic" /usr/local/bin/archangel-diagnostic

say
say "Installed:"
say "  /usr/local/bin/archangel-access"
say "  /usr/local/bin/archangel-diagnostic"
say "  /etc/archangel.conf"
say
say "Agent account: $agent_user"
say "Owner account: $owner_user"
say "Journal access: $journal_enabled"
say
say "Suggested next steps:"
say "  sudo archangel-access status"
say "  sudo archangel-access check /home/$owner_user/.ssh"
say "  sudo -u $agent_user -H archangel-diagnostic"
say
say "To share a config tree later:"
say "  sudo archangel-access grant rw /home/$owner_user/.config/hypr"
say
say "See docs/first-task.md for a cautious first agent task."
